spring:
  application:
    name: money-raven
#  h2:
#    console:
#      enabled: true
#      path: /h2
#      settings:
#        web-allow-others: true
  datasource:
#    url: jdbc:h2:file:~/test
    url: jdbc:h2:tcp://localhost:1521/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate.ddl-auto: none
